// This file is auto-generated by `cargo run -- --export-bindings`.
// Do not edit by hand — update the Rust command signatures and regenerate.
// Specta rc.24 serde_json::Value TS-emission workaround.
type Value = unknown;
type Vec<T> = T[];

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "./api";

/** Commands */
export const commands = {
	spawnAgent: (req: SpawnAgentRequest) => typedError<null, ErrorDto>(__TAURI_INVOKE("spawn_agent", { req })),
	sendCommand: (id: string, commandJson: string) => typedError<null, ErrorDto>(__TAURI_INVOKE("send_command", { id, commandJson })),
	killAgent: (id: string, graceful: boolean | null) => typedError<null, ErrorDto>(__TAURI_INVOKE("kill_agent", { id, graceful })),
	/**
	 *  Return the current assembled live state for an agent. This is the "pull"
	 *  half of the pull-then-subscribe pattern: Phase 2's frontend calls this on
	 *  mount to seed `liveAgentStore`, then listens on `agent-state-{id}` for
	 *  subsequent updates and reconciles by `stateVersion`.
	 * 
	 *  Returns `None` if no entry exists for this agent (no events have arrived
	 *  yet, or the agent was killed). Callers should treat `None` as "empty
	 *  state" rather than an error.
	 */
	getAgentState: (agentId: string) => typedError<{
	items: DisplayItem[],
	/**
	 *  Flat map from tool call id → execution. Serializes as a JS object.
	 *  Phase 2's store adapter converts to a `Map` before handing to tool
	 *  components so the `AgentContext.live` shape stays frozen.
	 */
	toolExecutions: { [key in string]: ToolExecution },
	streamingMessage: StreamingMessage | null,
	lastUsage: Usage | null,
	activityStatus: string,
	eventCount: number,
	/**
	 *  Set to true when the reader hit a parse failure or an out-of-order
	 *  event it could not reconcile. Reset to false on the next `message_start`.
	 */
	desynced: boolean,
	/**
	 *  Monotonically increasing per-agent. The frontend reconciles by dropping
	 *  any incoming snapshot whose version is <= its current entry version.
	 */
	stateVersion: number,
	/**
	 *  True while the agent is actively producing a turn. Drives the Abort
	 *  button and the `ChatInput` disabled state on the frontend, plus the
	 *  status dots in Sidebar/TabBar. Flipped on in `apply_event` at
	 *  `MessageStart { assistant }` and `ToolExecutionStart`, off at
	 *  `AgentEnd`. Tighter boundaries (`TurnEnd`, `MessageEnd`,
	 *  `ToolExecutionEnd`) are intentionally avoided to prevent mid-turn
	 *  flicker while tools run or the next LLM call spins up — a turn is
	 *  not "done" until the agent stops talking and tools stop running.
	 *  If Pi SDK ever starts firing `MessageEnd` mid-agent-turn (parallel
	 *  tool calls) this policy needs to be revisited — see MON-40.
	 */
	isStreaming: boolean,
} | null, ErrorDto>(__TAURI_INVOKE("get_agent_state", { agentId })),
	/**
	 *  Rebuild the assembled `LiveAgentState` for an agent from a SQLite session
	 *  and publish a snapshot on `agent-state-{id}`. Returns the new state so the
	 *  frontend can seed its store without waiting for the event loopback.
	 * 
	 *  `session_id = None` clears the state (used for "new session" flows).
	 */
	rebuildAgentStateFromSession: (agentId: string, sessionId: string | null, statusText: string) => typedError<LiveAgentState, ErrorDto>(__TAURI_INVOKE("rebuild_agent_state_from_session", { agentId, sessionId, statusText })),
	/**
	 *  Load messages from a previous SQLite session into the sidecar's agent context.
	 *  This gives the LLM conversational continuity when restoring.
	 */
	loadSessionContext: (agentId: string, sourceSessionId: string) => typedError<null, ErrorDto>(__TAURI_INVOKE("load_session_context", { agentId, sourceSessionId })),
	/**
	 *  Create a new session for an existing agent.
	 *  Creates a DB row, updates the agent→session mapping, and tells the sidecar to reset.
	 */
	newAgentSession: (agentId: string, newSessionId: string, parentSessionId: string | null) => typedError<null, ErrorDto>(__TAURI_INVOKE("new_agent_session", { agentId, newSessionId, parentSessionId })),
	/**
	 *  Switch an agent to an existing persisted session instead of creating a new one.
	 *  Resets the sidecar's in-memory conversation and updates DB/session routing so
	 *  subsequent messages are appended to the selected session.
	 */
	switchAgentSession: (agentId: string, sessionId: string) => typedError<null, ErrorDto>(__TAURI_INVOKE("switch_agent_session", { agentId, sessionId })),
	// Forward extension UI response from frontend to sidecar
	respondExtensionUi: (req: ExtensionUiResponseRequest) => typedError<null, ErrorDto>(__TAURI_INVOKE("respond_extension_ui", { req })),
	getModels: (provider: string, forceRefresh: boolean | null) => typedError<ModelInfo[], ErrorDto>(__TAURI_INVOKE("get_models", { provider, forceRefresh })),
	getProviderAuthStatus: (provider: string) => typedError<ProviderAuthStatus, ErrorDto>(__TAURI_INVOKE("get_provider_auth_status", { provider })),
	getAgentPrompt: (agentId: string) => typedError<string | null, ErrorDto>(__TAURI_INVOKE("get_agent_prompt", { agentId })),
	saveAgentPrompt: (agentId: string, prompt: string) => typedError<null, ErrorDto>(__TAURI_INVOKE("save_agent_prompt", { agentId, prompt })),
	getPromptsDir: () => typedError<string, ErrorDto>(__TAURI_INVOKE("get_prompts_dir")),
	/**
	 *  MON-73: Copy a user-selected image file into the Monarch avatars directory,
	 *  naming it after the agent. Returns the stored absolute path.
	 */
	saveAvatarImage: (agentId: string, srcPath: string) => typedError<string, ErrorDto>(__TAURI_INVOKE("save_avatar_image", { agentId, srcPath })),
	/**
	 *  MON-73: Read a saved avatar image and return it as a base64 data URL.
	 *  Lets the webview display local filesystem images without needing the Tauri
	 *  asset protocol to be scoped, which requires additional capability config.
	 */
	readAvatarDataUrl: (path: string) => typedError<string, ErrorDto>(__TAURI_INVOKE("read_avatar_data_url", { path })),
	/**
	 *  MON-75: Read a saved chat-message attachment and return it as a base64
	 *  data URL. Mirrors `read_avatar_data_url` but is keyed on an arbitrary
	 *  path (attachments live under stable UUIDs, not an entity id).
	 */
	readAttachmentDataUrl: (path: string) => typedError<string, ErrorDto>(__TAURI_INVOKE("read_attachment_data_url", { path })),
	dbUpsertAgent: (agent: AgentRow) => typedError<null, ErrorDto>(__TAURI_INVOKE("db_upsert_agent", { agent })),
	// MON-73: Update user-editable agent fields without touching spawn-time fields.
	dbUpdateAgent: (payload: AgentUpdatePayload) => typedError<null, ErrorDto>(__TAURI_INVOKE("db_update_agent", { payload })),
	dbGetAgents: (includeArchived: boolean | null) => typedError<AgentRow[], ErrorDto>(__TAURI_INVOKE("db_get_agents", { includeArchived })),
	dbArchiveAgent: (agentId: string) => typedError<null, ErrorDto>(__TAURI_INVOKE("db_archive_agent", { agentId })),
	dbUnarchiveAgent: (agentId: string) => typedError<null, ErrorDto>(__TAURI_INVOKE("db_unarchive_agent", { agentId })),
	dbDeleteAgent: (agentId: string) => typedError<null, ErrorDto>(__TAURI_INVOKE("db_delete_agent", { agentId })),
	dbCreateSession: (session: SessionRow) => typedError<null, ErrorDto>(__TAURI_INVOKE("db_create_session", { session })),
	dbGetSessions: (agentId: string) => typedError<SessionRow[], ErrorDto>(__TAURI_INVOKE("db_get_sessions", { agentId })),
	dbSaveMessage: (message: MessageRow) => typedError<number, ErrorDto>(__TAURI_INVOKE("db_save_message", { message })),
	dbGetMessages: (sessionId: string) => typedError<MessageRow[], ErrorDto>(__TAURI_INVOKE("db_get_messages", { sessionId })),
	// Get messages for a session, including all ancestor sessions (for continued sessions)
	dbGetMessagesWithAncestry: (sessionId: string) => typedError<MessageRow[], ErrorDto>(__TAURI_INVOKE("db_get_messages_with_ancestry", { sessionId })),
	dbSaveMemory: (memory: MemoryRow) => typedError<number, ErrorDto>(__TAURI_INVOKE("db_save_memory", { memory })),
	dbGetMemories: (agentId: string | null, layer: string | null) => typedError<MemoryRow[], ErrorDto>(__TAURI_INVOKE("db_get_memories", { agentId, layer })),
	dbLogEvent: (agentId: string | null, sessionId: string | null, eventType: string, data: string | null) => typedError<null, ErrorDto>(__TAURI_INVOKE("db_log_event", { agentId, sessionId, eventType, data })),
	dbListAgentTemplates: () => typedError<AgentTemplateRow[], ErrorDto>(__TAURI_INVOKE("db_list_agent_templates")),
	dbSaveAgentTemplate: (template: AgentTemplateRow) => typedError<null, ErrorDto>(__TAURI_INVOKE("db_save_agent_template", { template })),
	dbDeleteAgentTemplate: (templateId: string) => typedError<null, ErrorDto>(__TAURI_INVOKE("db_delete_agent_template", { templateId })),
	dbUpsertProject: (project: ProjectRow) => typedError<null, ErrorDto>(__TAURI_INVOKE("db_upsert_project", { project })),
	dbGetProjects: () => typedError<ProjectRow[], ErrorDto>(__TAURI_INVOKE("db_get_projects")),
	dbGetProjectByPath: (rootPath: string) => typedError<{
	id: string,
	name: string,
	rootPath: string,
	instructions: string | null,
	createdAt: string,
	updatedAt: string,
} | null, ErrorDto>(__TAURI_INVOKE("db_get_project_by_path", { rootPath })),
	dbRenameProject: (projectId: string, name: string) => typedError<null, ErrorDto>(__TAURI_INVOKE("db_rename_project", { projectId, name })),
	dbUpdateProjectInstructions: (projectId: string, instructions: string | null) => typedError<null, ErrorDto>(__TAURI_INVOKE("db_update_project_instructions", { projectId, instructions })),
	dbDeleteProject: (projectId: string) => typedError<null, ErrorDto>(__TAURI_INVOKE("db_delete_project", { projectId })),
	detectProject: (cwd: string) => typedError<"Null" | ({ Bool: boolean }) & { Array?: never; Number?: never; Object?: never; String?: never } | ({ Number: ({ f64: number }) & { i64?: never; u64?: never } | ({ i64: number }) & { f64?: never; u64?: never } | ({ u64: number }) & { f64?: never; i64?: never } }) & { Array?: never; Bool?: never; Object?: never; String?: never } | ({ String: string }) & { Array?: never; Bool?: never; Number?: never; Object?: never } | ({ Array: ("Null" | ({ Bool: boolean }) & { Array?: never; Number?: never; Object?: never; String?: never } | ({ Number: ({ f64: number }) & { i64?: never; u64?: never } | ({ i64: number }) & { f64?: never; u64?: never } | ({ u64: number }) & { f64?: never; i64?: never } }) & { Array?: never; Bool?: never; Object?: never; String?: never } | ({ String: string }) & { Array?: never; Bool?: never; Number?: never; Object?: never } | ({ Array: Vec<Value> }) & { Bool?: never; Number?: never; Object?: never; String?: never } | ({ Object: { [key in string]: Value } }) & { Array?: never; Bool?: never; Number?: never; String?: never })[] }) & { Bool?: never; Number?: never; Object?: never; String?: never } | ({ Object: { [key in string]: "Null" | ({ Bool: boolean }) & { Array?: never; Number?: never; Object?: never; String?: never } | ({ Number: ({ f64: number }) & { i64?: never; u64?: never } | ({ i64: number }) & { f64?: never; u64?: never } | ({ u64: number }) & { f64?: never; i64?: never } }) & { Array?: never; Bool?: never; Object?: never; String?: never } | ({ String: string }) & { Array?: never; Bool?: never; Number?: never; Object?: never } | ({ Array: Value[] }) & { Bool?: never; Number?: never; Object?: never; String?: never } | ({ Object: Map<string, Value> }) & { Array?: never; Bool?: never; Number?: never; String?: never } } }) & { Array?: never; Bool?: never; Number?: never; String?: never } | null, ErrorDto>(__TAURI_INVOKE("detect_project", { cwd })),
	readProjectInstructions: (cwd: string) => typedError<string | null, ErrorDto>(__TAURI_INVOKE("read_project_instructions", { cwd })),
	/**
	 *  Tauri command wrapper. Walking is synchronous under the hood but the entry
	 *  count is bounded by `MAX_WALKED`, so running it on a blocking thread via
	 *  `spawn_blocking` keeps the async runtime unclogged on huge trees.
	 */
	listPaths: (cwd: string, query: string) => typedError<PathSuggestion[], ErrorDto>(__TAURI_INVOKE("list_paths", { cwd, query })),
	dbGetUiState: (key: string) => typedError<string | null, ErrorDto>(__TAURI_INVOKE("db_get_ui_state", { key })),
	dbSetUiState: (key: string, value: string) => typedError<null, ErrorDto>(__TAURI_INVOKE("db_set_ui_state", { key, value })),
	dbGetAgentStats: (agentId: string) => typedError<AgentStats, ErrorDto>(__TAURI_INVOKE("db_get_agent_stats", { agentId })),
	toolboxListTools: () => __TAURI_INVOKE<ToolDescriptor[]>("toolbox_list_tools"),
	toolboxPlaceholderPing: () => typedError<string, ErrorDto>(__TAURI_INVOKE("toolbox_placeholder_ping")),
	setZoom: (level: number) => typedError<number, ErrorDto>(__TAURI_INVOKE("set_zoom", { level })),
	getThinkingDefault: (provider: string, model: string) => typedError<string, ErrorDto>(__TAURI_INVOKE("get_thinking_default", { provider, model })),
	getThinkingConfigPath: () => typedError<string, ErrorDto>(__TAURI_INVOKE("get_thinking_config_path")),
};

/* Types */
export type AgentRow = {
	id: string,
	name: string,
	projectId: string | null,
	shadowName: string | null,
	shadowTitle: string | null,
	shadowGrade: string | null,
	provider: string | null,
	model: string | null,
	thinkingLevel: string | null,
	cwd: string | null,
	customPrompt: string | null,
	// User-supplied context window (tokens). Currently only used for lmstudio.
	contextWindow: number | null,
	createdAt: string,
	updatedAt: string,
	/**
	 *  MON-66: ISO timestamp when the agent was archived, or None if active.
	 *  Archive preserves the DB row (history, sessions, stats) but removes
	 *  the shadow from the default active roster. See `archive_agent_internal`.
	 */
	archivedAt: string | null,
	// MON-73: "rive" | "image" | null (null = default rive preset).
	avatarType: string | null,
	/**
	 *  MON-73: For "rive": path to .riv file (null = default). For "image":
	 *  built-in web path ("/avatars/foo.png") or absolute filesystem path.
	 */
	avatarPath: string | null,
};

export type AgentStats = {
	agentId: string,
	totalSessions: number,
	totalMessages: number,
	totalTurns: number,
	totalInputTokens: number,
	totalOutputTokens: number,
	totalCost: number,
	// Normalized experience level 0-100, derived from total tokens (log scale).
	experience: number,
	toolUsage: ToolUsageEntry[],
	specialization: SpecializationScores,
	updatedAt: string,
};

export type AgentTemplateRow = {
	id: string,
	name: string,
	provider: string | null,
	model: string | null,
	thinkingLevel: string | null,
	cwd: string | null,
	shadowName: string | null,
	shadowTitle: string | null,
	shadowGrade: string | null,
	createdAt: string,
	updatedAt: string,
};

// MON-73: Payload for updating editable agent fields post-creation.
export type AgentUpdatePayload = {
	id: string,
	name: string,
	shadowName: string | null,
	shadowTitle: string | null,
	shadowGrade: string | null,
	provider: string | null,
	model: string | null,
	thinkingLevel: string | null,
	cwd: string | null,
	avatarType: string | null,
	avatarPath: string | null,
};

export type Cost = {
	input?: number,
	output?: number,
	total?: number,
};

export type DisplayItem = { kind: "user"; content: string; timestamp: number | null; 
/**
 *  MON-75: image attachments that were sent with this user
 *  message. Populated for snapshots rebuilt from SQLite (via
 *  `display_items_from_messages`); empty for messages assembled
 *  live from sidecar events, since the frontend still holds the
 *  data-URL ephemerally until the DB round-trip lands.
 */
attachments?: MessageAttachmentRow[] } | { kind: "assistant"; content: ("Null" | ({ Bool: boolean }) & { Array?: never; Number?: never; Object?: never; String?: never } | ({ Number: ({ f64: number }) & { i64?: never; u64?: never } | ({ i64: number }) & { f64?: never; u64?: never } | ({ u64: number }) & { f64?: never; i64?: never } }) & { Array?: never; Bool?: never; Object?: never; String?: never } | ({ String: string }) & { Array?: never; Bool?: never; Number?: never; Object?: never } | ({ Array: Vec<Value> }) & { Bool?: never; Number?: never; Object?: never; String?: never } | ({ Object: { [key in string]: Value } }) & { Array?: never; Bool?: never; Number?: never; String?: never })[]; model: string | null; usage: Usage | null; timestamp: number | null; 
/**
 *  MON-71: turn wall-clock duration, set when `MessageEnd` fires.
 *  Persisted on the `messages.duration_ms` column; restored by
 *  `display_items_from_messages`. None for pre-MON-71 rows.
 */
durationMs?: number | null } | { kind: "tool-group"; executions: ToolExecution[]; turnComplete: boolean } | { kind: "status"; text: string } | { kind: "notification"; text: string; level: NotificationLevel };

export type ErrorDto = {
	kind: string,
	message: string,
	details: string | null,
};

/**
 *  Request payload for the `respond_extension_ui` Tauri command. MON-33 folds
 *  the three scattered `agent_id` / `request_id` / `value` args into a single
 *  typed struct so both the IPC and WS transports decode the same shape.
 *  `value` stays `serde_json::Value` because the extension UI contract is
 *  intentionally open-ended — different widget kinds return different payloads
 *  and the sidecar is the ultimate authority on shape validation.
 */
export type ExtensionUiResponseRequest = {
	agentId: string,
	requestId: string,
	value: "Null" | ({ Bool: boolean }) & { Array?: never; Number?: never; Object?: never; String?: never } | ({ Number: ({ f64: number }) & { i64?: never; u64?: never } | ({ i64: number }) & { f64?: never; u64?: never } | ({ u64: number }) & { f64?: never; i64?: never } }) & { Array?: never; Bool?: never; Object?: never; String?: never } | ({ String: string }) & { Array?: never; Bool?: never; Number?: never; Object?: never } | ({ Array: Value[] }) & { Bool?: never; Number?: never; Object?: never; String?: never } | ({ Object: { [key in string]: Value } }) & { Array?: never; Bool?: never; Number?: never; String?: never },
};

export type LiveAgentState = {
	items: DisplayItem[],
	/**
	 *  Flat map from tool call id → execution. Serializes as a JS object.
	 *  Phase 2's store adapter converts to a `Map` before handing to tool
	 *  components so the `AgentContext.live` shape stays frozen.
	 */
	toolExecutions: { [key in string]: ToolExecution },
	streamingMessage: StreamingMessage | null,
	lastUsage: Usage | null,
	activityStatus: string,
	eventCount: number,
	/**
	 *  Set to true when the reader hit a parse failure or an out-of-order
	 *  event it could not reconcile. Reset to false on the next `message_start`.
	 */
	desynced: boolean,
	/**
	 *  Monotonically increasing per-agent. The frontend reconciles by dropping
	 *  any incoming snapshot whose version is <= its current entry version.
	 */
	stateVersion: number,
	/**
	 *  True while the agent is actively producing a turn. Drives the Abort
	 *  button and the `ChatInput` disabled state on the frontend, plus the
	 *  status dots in Sidebar/TabBar. Flipped on in `apply_event` at
	 *  `MessageStart { assistant }` and `ToolExecutionStart`, off at
	 *  `AgentEnd`. Tighter boundaries (`TurnEnd`, `MessageEnd`,
	 *  `ToolExecutionEnd`) are intentionally avoided to prevent mid-turn
	 *  flicker while tools run or the next LLM call spins up — a turn is
	 *  not "done" until the agent stops talking and tools stop running.
	 *  If Pi SDK ever starts firing `MessageEnd` mid-agent-turn (parallel
	 *  tool calls) this policy needs to be revisited — see MON-40.
	 */
	isStreaming: boolean,
};

export type MemoryRow = {
	id: number,
	agentId: string | null,
	layer: string,
	category: string,
	content: string,
	relevance: number,
	createdAt: string,
	lastAccessed: string | null,
	accessCount: number,
};

/**
 *  MON-75: one row in `message_attachments`. Exposed to the frontend so
 *  the display snapshot can surface attachment paths to MessageList for
 *  rendering; the webview resolves each path through the
 *  `read_attachment_data_url` command.
 */
export type MessageAttachmentRow = {
	path: string,
	mimeType: string,
	position: number,
};

export type MessageRow = {
	id: number,
	sessionId: string,
	role: string,
	content: string,
	model: string | null,
	tokens: number,
	cost: number,
	timestamp: string,
	/**
	 *  MON-71: wall-clock duration of the assistant turn that produced this
	 *  message, in milliseconds. NULL for rows written before MON-71, and for
	 *  roles other than `assistant` (user and toolResult carry their own
	 *  timing — tool durations live inside the toolResult JSON blob).
	 */
	durationMs?: number | null,
	/**
	 *  MON-75: image attachments persisted alongside user messages. Empty
	 *  for assistant/tool rows and for user messages without images.
	 *  Populated by `get_messages_with_ancestry`; ignored by writers
	 *  (`save_message_internal` never inserts attachments — that goes
	 *  through `save_message_attachment_internal`).
	 */
	attachments?: MessageAttachmentRow[],
};

export type ModelInfo = {
	id: string,
	name: string,
	provider: string,
	/**
	 *  Optional pre-detected context window in tokens. Only populated for
	 *  LM Studio entries discovered via the native `/api/v0/models` endpoint,
	 *  and only for models LM Studio reports as currently loaded.
	 */
	contextWindow: number | null,
};

export type NotificationLevel = "info" | "warning" | "error";

export type PathSuggestion = {
	/**
	 *  Path relative to the original `cwd`, always using forward slashes so
	 *  the inserted token looks the same on every platform.
	 */
	path: string,
	// True if the entry is a directory, false if it's a file.
	isDir: boolean,
};

export type ProjectRow = {
	id: string,
	name: string,
	rootPath: string,
	instructions: string | null,
	createdAt: string,
	updatedAt: string,
};

export type ProviderAuthStatus = {
	provider: string,
	checked: boolean,
	configured: boolean,
	source: string | null,
	message: string,
};

export type SessionRow = {
	id: string,
	agentId: string,
	piSessionFile: string | null,
	model: string | null,
	provider: string | null,
	startedAt: string,
	endedAt: string | null,
	messageCount: number,
	totalTokens: number,
	totalCost: number,
	parentSessionId: string | null,
};

/**
 *  Shadow identity block carried inside `SpawnAgentRequest`. Mirrors the
 *  frontend's nested `config.shadow` object (name/title/grade), which the
 *  backend then maps into the sidecar-facing `ShadowConfig` by injecting the
 *  synthesized agent id at command-build time.
 */
export type ShadowSpec = {
	shadowName: string | null,
	shadowTitle: string | null,
	shadowGrade: string | null,
};

/**
 *  Request payload for the `spawn_agent` Tauri command. Collapsing the ten
 *  per-field params into a struct keeps the command under specta's 10-arg
 *  `SpectaFn` cap so it can participate in typed binding generation — see
 *  `lib.rs::specta_builder` for the registration site.
 */
export type SpawnAgentRequest = {
	id: string,
	sessionId: string,
	provider: string | null,
	model: string | null,
	thinkingLevel: string | null,
	cwd: string | null,
	shadow: ShadowSpec | null,
	contextWindow: number | null,
};

export type SpecializationScores = {
	coding: number,
	research: number,
	testing: number,
	debugging: number,
	devops: number,
	documentation: number,
	database: number,
	configuration: number,
	design: number,
	communication: number,
	refactoring: number,
	security: number,
};

export type StreamingMessage = {
	content: ("Null" | ({ Bool: boolean }) & { Array?: never; Number?: never; Object?: never; String?: never } | ({ Number: ({ f64: number }) & { i64?: never; u64?: never } | ({ i64: number }) & { f64?: never; u64?: never } | ({ u64: number }) & { f64?: never; i64?: never } }) & { Array?: never; Bool?: never; Object?: never; String?: never } | ({ String: string }) & { Array?: never; Bool?: never; Number?: never; Object?: never } | ({ Array: Vec<Value> }) & { Bool?: never; Number?: never; Object?: never; String?: never } | ({ Object: { [key in string]: Value } }) & { Array?: never; Bool?: never; Number?: never; String?: never })[],
	model: string | null,
	usage: Usage | null,
	timestamp: number | null,
	/**
	 *  MON-71: wall-clock start of the current turn, stamped at `TurnStart`.
	 *  Drives the live "N sec" ticker on the streaming assistant header.
	 */
	turnStartedAtMs?: number | null,
};

export type ToolDescriptor = {
	id: string,
	title: string,
};

export type ToolExecution = {
	toolCallId: string,
	toolName: string,
	args: "Null" | ({ Bool: boolean }) & { Array?: never; Number?: never; Object?: never; String?: never } | ({ Number: ({ f64: number }) & { i64?: never; u64?: never } | ({ i64: number }) & { f64?: never; u64?: never } | ({ u64: number }) & { f64?: never; i64?: never } }) & { Array?: never; Bool?: never; Object?: never; String?: never } | ({ String: string }) & { Array?: never; Bool?: never; Number?: never; Object?: never } | ({ Array: Value[] }) & { Bool?: never; Number?: never; Object?: never; String?: never } | ({ Object: { [key in string]: Value } }) & { Array?: never; Bool?: never; Number?: never; String?: never } | null,
	result: "Null" | ({ Bool: boolean }) & { Array?: never; Number?: never; Object?: never; String?: never } | ({ Number: ({ f64: number }) & { i64?: never; u64?: never } | ({ i64: number }) & { f64?: never; u64?: never } | ({ u64: number }) & { f64?: never; i64?: never } }) & { Array?: never; Bool?: never; Object?: never; String?: never } | ({ String: string }) & { Array?: never; Bool?: never; Number?: never; Object?: never } | ({ Array: Value[] }) & { Bool?: never; Number?: never; Object?: never; String?: never } | ({ Object: { [key in string]: Value } }) & { Array?: never; Bool?: never; Number?: never; String?: never } | null,
	isError: boolean | null,
	status: ToolStatus,
	/**
	 *  MON-71: wall-clock start, stamped when `ToolExecutionStart` lands in
	 *  Rust. Drives the live "N sec" ticker while running and feeds
	 *  `duration_ms` on completion. None for historical rows restored from
	 *  pre-MON-71 SQLite (no backfill).
	 */
	startedAtMs?: number | null,
	/**
	 *  MON-71: final end-to-end duration; set at `ToolExecutionEnd`.
	 *  Preserved across restart via the tool-result JSON (`durationMs`).
	 */
	durationMs?: number | null,
};

export type ToolStatus = "running" | "done" | "error";

export type ToolUsageEntry = {
	toolName: string,
	callCount: number,
	errorCount: number,
};

export type Usage = {
	input?: number,
	output?: number,
	cacheRead?: number,
	cacheWrite?: number,
	totalTokens?: number,
	cost?: Cost,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

